<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ETT-Descriptor [
		<!ELEMENT ETT-Descriptor (ETT-TimeTable|ETT-EvolutionEngine)*>
		<!ATTLIST ETT-Descriptor
				xmlns:xsi CDATA #REQUIRED
				xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
		<!ELEMENT ETT-TimeTable (ETT-Teachers|ETT-Subjects|ETT-Classes|ETT-Rules)*>
		<!ATTLIST ETT-TimeTable
				days CDATA #REQUIRED
				hours CDATA #REQUIRED>
		<!ELEMENT ETT-Teachers (ETT-Teacher)*>
		<!ELEMENT ETT-Teacher (ETT-Name|ETT-Teaching)*>
		<!ATTLIST ETT-Teacher
				id CDATA #REQUIRED>
		<!ELEMENT ETT-Name (#PCDATA)>
		<!ELEMENT ETT-Teaching (ETT-Teaches)*>
		<!ELEMENT ETT-Teaches (#PCDATA)>
		<!ATTLIST ETT-Teaches
				subject-id CDATA #REQUIRED>
		<!ELEMENT ETT-Subjects (ETT-Subject)*>
		<!ELEMENT ETT-Subject (#PCDATA)>
		<!ATTLIST ETT-Subject
				id CDATA #REQUIRED
				name CDATA #REQUIRED>
		<!ELEMENT ETT-Classes (ETT-Class)*>
		<!ELEMENT ETT-Class (ETT-Name|ETT-Requirements)*>
		<!ATTLIST ETT-Class
				id CDATA #REQUIRED>
		<!ELEMENT ETT-Requirements (ETT-Study)*>
		<!ELEMENT ETT-Study (#PCDATA)>
		<!ATTLIST ETT-Study
				hours CDATA #REQUIRED
				subject-id CDATA #REQUIRED>
		<!ELEMENT ETT-Rules (ETT-Rule)*>
		<!ATTLIST ETT-Rules
				hard-rules-weight CDATA #REQUIRED>
		<!ELEMENT ETT-Rule (ETT-RuleId)*>
		<!ATTLIST ETT-Rule
				type CDATA #REQUIRED>
		<!ELEMENT ETT-RuleId (#PCDATA)>
		<!ELEMENT ETT-EvolutionEngine (ETT-InitialPopulation|ETT-Selection|ETT-Crossover|ETT-Mutations)*>
		<!ELEMENT ETT-InitialPopulation (#PCDATA)>
		<!ATTLIST ETT-InitialPopulation
				size CDATA #REQUIRED>
		<!ELEMENT ETT-Selection (#PCDATA)>
		<!ATTLIST ETT-Selection
				type CDATA #REQUIRED
				configuration CDATA #REQUIRED>
		<!ELEMENT ETT-Crossover (#PCDATA)>
		<!ATTLIST ETT-Crossover
				name CDATA #REQUIRED
				cutting-points CDATA #REQUIRED>
		<!ELEMENT ETT-Mutations (ETT-Mutation)*>
		<!ELEMENT ETT-Mutation (#PCDATA)>
		<!ATTLIST ETT-Mutation
				configuration CDATA #REQUIRED
				name CDATA #REQUIRED
				probability CDATA #REQUIRED>
		]>
<ETT-Descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ETT-V1.xsd">
	<ETT-TimeTable days="4" hours="5">
		<ETT-Teachers>
			<ETT-Teacher id="1">
				<ETT-Name>Asi Mon</ETT-Name>
				<ETT-Teaching>
					<ETT-Teaches subject-id="1"/>
					<ETT-Teaches subject-id="2"/>
				</ETT-Teaching>
			</ETT-Teacher>
			<ETT-Teacher id="3">
				<ETT-Name>Tim Sorly</ETT-Name>
				<ETT-Teaching>
					<ETT-Teaches subject-id="3"/>
				</ETT-Teaching>
			</ETT-Teacher>			
			<ETT-Teacher id="2">
				<ETT-Name>Sima Zgan</ETT-Name>
				<ETT-Teaching>
					<ETT-Teaches subject-id="2"/>
					<ETT-Teaches subject-id="3"/>
				</ETT-Teaching>
			</ETT-Teacher>						
			<ETT-Teacher id="4">
				<ETT-Name>Sami Pokvar</ETT-Name>
				<ETT-Teaching>
					<ETT-Teaches subject-id="2"/>
					<ETT-Teaches subject-id="4"/>
				</ETT-Teaching>
			</ETT-Teacher>									
		</ETT-Teachers>
		<ETT-Subjects>
			<ETT-Subject id="1" name="Sifrut"/>
			<ETT-Subject id="3" name="Tanach"/>
			<ETT-Subject id="4" name="English"/>
			<ETT-Subject id="2" name="Math"/>
		</ETT-Subjects>		
		<ETT-Classes>
			<ETT-Class id="1">
				<ETT-Name>Standart</ETT-Name>
				<ETT-Requirements>
					<ETT-Study subject-id="1" hours="3"/>
					<ETT-Study subject-id="2" hours="4"/>
					<ETT-Study subject-id="3" hours="2"/>
				</ETT-Requirements>
			</ETT-Class>
			<ETT-Class id="2">
				<ETT-Name>Nerds</ETT-Name>
				<ETT-Requirements>
					<ETT-Study subject-id="2" hours="6"/>
					<ETT-Study subject-id="4" hours="6"/>
				</ETT-Requirements>
			</ETT-Class>			
			<ETT-Class id="3">
				<ETT-Name>Tikshoret</ETT-Name>
				<ETT-Requirements>
					<ETT-Study subject-id="4" hours="2"/>
					<ETT-Study subject-id="1" hours="4"/>
					<ETT-Study subject-id="3" hours="6"/>
					<ETT-Study subject-id="2" hours="4"/>
				</ETT-Requirements>
			</ETT-Class>			
			<ETT-Class id="4">
				<ETT-Name>Biologit</ETT-Name>
				<ETT-Requirements>
					<ETT-Study subject-id="4" hours="2"/>
					<ETT-Study subject-id="2" hours="4"/>
				</ETT-Requirements>
			</ETT-Class>					
		</ETT-Classes>
		<ETT-Rules hard-rules-weight="70">
			<ETT-Rule type="Hard">
				<ETT-RuleId>TeacherIsHuman</ETT-RuleId>
			</ETT-Rule>
			<ETT-Rule type="Hard">
				<ETT-RuleId>Singularity</ETT-RuleId>
			</ETT-Rule>
			<ETT-Rule type="Hard">
				<ETT-RuleId>Satisfactory</ETT-RuleId>
			</ETT-Rule>
			<ETT-Rule type="Soft">
				<ETT-RuleId>Knowledgeable</ETT-RuleId>
			</ETT-Rule>
		</ETT-Rules>
	</ETT-TimeTable>
	<ETT-EvolutionEngine>
		<ETT-InitialPopulation size="200"/>
		<ETT-Selection type="Truncation" configuration="TopPercent=10"/>
		<ETT-Crossover name="DayTimeOriented" cutting-points="2"/>
		<ETT-Mutations>
			<ETT-Mutation name="Flipping" probability="0.3" configuration="MaxTupples=3,Component=T"/>
			<ETT-Mutation name="Flipping" probability="0.3" configuration="MaxTupples=3,Component=C"/>
			<ETT-Mutation name="Flipping" probability="0.3" configuration="MaxTupples=3,Component=S"/>			
		</ETT-Mutations>
	</ETT-EvolutionEngine>
</ETT-Descriptor>
